### ISSUE TITLE
Robustness to interrupted connection

### ISSUE THREAD

**Issue by OndroV** [DominikBuchner/BOLDigger3#10]
Hi, could it be true that the performance of boldigger3 is less robust to interrupted internet connection? I dont have any tests, but it feels so:
With boldigger2 I could normally put the pc in sleep mode or move around, and the process would simply continue when connection was reestabilished. This morning, boldigger3 crashed twice probably because I moved from home to work and then around the faculty.
By the way, the sequences are queued again, except those that had json data downloaded in the meantime. Does bold analyze those interrupted requests? I can imagine problems with requeuing over and over during downtimes, when we would restart the process and overload the capacities even more. Perhaps some links to the queued jobs could be stored and revisited after restarting the process?
[connection_interrupted.txt](https://github.com/user-attachments/files/17616109/connection_interrupted.txt)

**Comment by DominikBuchner** [comment]
Hi Ondrej,
it's tough to build a webscraper that is stable even when internet connection is interrupted. I thought about storing the urls BUT the seem not to last forever, meaning in addition to checking if the data is downloaded I'd also need a failsafe for when the link is no longer available. I'll think about a solution in the future, however from my experience the download times are no longer the limiting factor and even for insane datasets like 50k OTUs do not take longer than a day.

So yes, while I agree that it would make perfect sense to store the queued jobs, it's hard to implement. I'll leave this open as enhancement and think about it.

**Comment by DominikBuchner** [comment]
I'm working on an update regarding the issue. BOLD is indeed slow at the
moment but I'm planing to store the already queued sequences so that
boldigger first tries to finish the old cue. Hope to get this going over
the weekend.

Joel Hjärne Kokk ***@***.***> schrieb am Fr., 8. Nov. 2024,
21:21:

**Comment by DominikBuchner** [comment]
![image](https://github.com/user-attachments/assets/782654d0-8f57-4f36-afb5-f2531c16b1b6)

Restarting in the morning after queuing sequences in the evening works like a charm. Requires a bit of planing ahead, but the PC can simply be shut down, and BOLDigger will continue where it left off, while the load is computed on the BOLD server.

**Comment by hjarnek** [comment]
Yes, can confirm this works great! Thanks Dominik! I put it on last night, but it took until this morning until the first result was collected. Probably something on BOLD's part. Now it rolls on smoothly, ~200 s/it.

**Comment by DominikBuchner** [comment]
Only appears to affect mode 3 imho. However, I think we can live with that :)

**Comment by OndroV** [comment]
Many thanks Dominik! BOLDigger's sustainability score improved by 10 points now that we can now save energy by turning our PCs off until BOLD responds :)

**Comment by hjarnek** [comment]
@DominikBuchner : I would just like to add a little thing here. Even though the download links are now saved, and BOLDigger3 resumes interrupted downloads graciously, this still has to be monitored and re-queried manually. It's not only about the stability of one's own internet connection, but I at least am seeing RemoteDisconnected errors every now and then. Would it be possible to add a `--retry` flag or similar, that automatically re-executes the last boldigger3 command in case of an error? So you can go to bed and sleep well :)

**Comment by DominikBuchner** [comment]
Hi Joel,

I retry on timeout but can do the same on Remote disconnect. I would need
the specific exception that is thrown, than I can certainly implement.

Joel Hjärne Kokk ***@***.***> schrieb am Di., 12. Nov. 2024,
22:12:

**Comment by hjarnek** [comment]
Sounds great! Here you go:

<details>
<summary>RemoteDisconnected error</summary>

```bash
Downloading JSON data:   3%|████▏                                                                                                                      | 15/447 [1:18:02<37:27:23, 312.14s/it]
Traceback (most recent call last):
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joel/.conda/envs/boldigger/bin/boldigger3", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/boldigger3/__main__.py", line 112, in main
    id_engine.main(
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/boldigger3/id_engine.py", line 523, in main
    download_json(
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/boldigger3/id_engine.py", line 395, in download_json
    download_and_parse(
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/boldigger3/id_engine.py", line 240, in download_and_parse
    response = html_session.get(download_url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
</details>

And another error I got which made me have to resume manually:

<details>
<summary>Playwright timeout error</summary>

```bash
Downloading JSON data:  27%|██████████████████████████████████▊                                                                                            | 81/296 [36:41<1:37:24, 27.18s/it]
Traceback (most recent call last):
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/boldigger3/id_engine.py", line 389, in download_json
    page.wait_for_selector("#jsonlResults", timeout=60000)
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 8165, in wait_for_selector
    self._sync(
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/playwright/_impl/_page.py", line 426, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 60000ms exceeded.
Call log:
waiting for locator("#jsonlResults") to be visible
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joel/.conda/envs/boldigger/bin/boldigger3", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/boldigger3/__main__.py", line 112, in main
    id_engine.main(
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/boldigger3/id_engine.py", line 523, in main
    download_json(
  File "/home/joel/.conda/envs/boldigger/lib/python3.12/site-packages/boldigger3/id_engine.py", line 422, in download_json
    queued = page.query_selector("#progress-queued").text_content()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text_content'
```
</details>

**Comment by OndroV** [comment]
I also experienced another one before opening this issue:

08:00:20: Reading input fasta.
08:00:20: Generating requests.
Queuing sequences in ID engine: 100%|█████████████████████████████████████████| 18341/18341 [11:07<00:00, 27.49it/s]
08:11:27: Waiting for results to load.
08:15:57: Result 1 of 184 collected.
Downloading JSON data:   1%|▎                                                 | 1/184 [47:41<145:26:22, 2861.11s/it]
Traceback (most recent call last):
  File "C:\Users\ondre\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ondre\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ondre\AppData\Local\Programs\Python\Python310\lib\site-packages\boldigger3\__main__.py", line 125, in <module>
    main()
  File "C:\Users\ondre\AppData\Local\Programs\Python\Python310\lib\site-packages\boldigger3\__main__.py", line 112, in main
    id_engine.main(
  File "C:\Users\ondre\AppData\Local\Programs\Python\Python310\lib\site-packages\boldigger3\id_engine.py", line 468, in main
    download_json(results_urls, hdf_name_results, database, operating_mode)
  File "C:\Users\ondre\AppData\Local\Programs\Python\Python310\lib\site-packages\boldigger3\id_engine.py", line 377, in download_json
    page.goto(url)
  File "C:\Users\ondre\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 9002, in goto
    self._sync(
  File "C:\Users\ondre\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "C:\Users\ondre\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_page.py", line 553, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\ondre\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\ondre\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\ondre\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.goto: net::ERR_NETWORK_IO_SUSPENDED at https://id.boldsystems.org/processing/db_all.bin-tax-derep~mi_0.85~mo_100~maxh_100~order_3-cdd08a60b922418c973c38e9114f7652
Call log:
navigating to "https://id.boldsystems.org/processing/db_all.bin-tax-derep~mi_0.85~mo_100~maxh_100~order_3-cdd08a60b922418c973c38e9114f7652", waiting until "load"

**Comment by DominikBuchner** [comment]
mostly fixed with v1.2.6
