### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text_content'

### ISSUE THREAD

**Issue by francielleholtz** [DominikBuchner/BOLDigger3#14]
Hello,

Unfortunately, I am getting the following error and am unsure if it is something I need to do or if it is boldigger3-related.

Thank you for the help.

Downloading JSON data:  10%|█          | 1/10 [11:08:36<100:17:25, 40116.15s/it]
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/boldigger3/id_engine.py", line 389, in download_json
    page.wait_for_selector("#jsonlResults", timeout=60000)
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 8165, in wait_for_selector
    self._sync(
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/playwright/_impl/_page.py", line 426, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 60000ms exceeded.
Call log:
waiting for locator("#jsonlResults") to be visible
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>
  -   locator resolved to hidden <a href="" id="jsonlResults" visibility="hidden">↵                              JSONL Results Down…</a>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/bin/boldigger3", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/boldigger3/__main__.py", line 112, in main
    id_engine.main(
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/boldigger3/id_engine.py", line 523, in main
    download_json(
  File "/opt/homebrew/anaconda3/lib/python3.12/site-packages/boldigger3/id_engine.py", line 422, in download_json
    queued = page.query_selector("#progress-queued").text_content()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text_content'

**Comment by DominikBuchner** [comment]
Fixed with 1.2.1
