### ISSUE TITLE
Getting "Connection broken" error with multiple restarts

### ISSUE THREAD

**Issue by Anto007** [DominikBuchner/BOLDigger3#17]
Hi @DominikBuchner 

Today I'm getting the below "Connection broken" error despite restarting this run for the 6th time for a 7K COI ASV dataset of mine. I'm using the latest available version 1.2.2 of BOLDigger3. I will be very grateful if you've got any ideas to improve this situation.

```
12:35:52: Reading input fasta.
12:37:06: Data download finished.
12:37:06: Collecting process ids.
12:37:07: Divided 23751 unique process ids into 3 batch(es) for download.
12:37:07: Downloading batch 1 of 3.
Downloading additional data:  10%|██▊                          | 960/10000 [02:39<1:43:31,  1.46it/s]Traceback (most recent call last):
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/urllib3/response.py", line 748, in _error_catcher
    yield
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/urllib3/response.py", line 894, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(0 bytes read, 41 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/urllib3/response.py", line 1060, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/urllib3/response.py", line 949, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/urllib3/response.py", line 872, in _raw_read
    with self._error_catcher():
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/urllib3/response.py", line 772, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read, 41 more expected)', IncompleteRead(0 bytes read, 41 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/tools/conda_python3.11_env/bin/boldigger3", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/boldigger3/__main__.py", line 118, in main
    additional_data_download.main(arguments.fasta_file)
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/boldigger3/additional_data_download.py", line 334, in main
    response = asyncio.run(as_session(chunk, semaphore))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/boldigger3/additional_data_download.py", line 203, in as_session
    return await tqdm.gather(*tasks, desc="Downloading additional data")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/tqdm/asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/tqdm/asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
           ^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/asyncio/tasks.py", line 615, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
              ^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/boldigger3/additional_data_download.py", line 170, in limit_concurrency
    return await as_request(url, as_session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/boldigger3/additional_data_download.py", line 146, in as_request
    response = await as_session.get(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/requests/models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read, 41 more expected)', IncompleteRead(0 bytes read, 41 more expected))
Downloading additional data:  10%|██▉                            | 960/10000 [03:16<30:49,  4.89it/s]
```

**Comment by DominikBuchner** [comment]
Hi, 
does this always happen at the same point in during the download, or at different points?

**Comment by Anto007** [comment]
The below is from a reattempt a minute ago. The above error showed 10% (960/10000) while the below latest one stopped at 8% (850/10000). Hope this is what you asked?

```
raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read, 50821 more expected)', IncompleteRead(0 bytes read, 50821 more expected))
Downloading additional data:   8%|██▋                            | 850/10000 [03:16<35:20,  4.32it/s]
```

**Comment by Anto007** [comment]
and I'm using db & mode-3

**Comment by DominikBuchner** [comment]
Yes, that's what I needed to know :)

**Comment by DominikBuchner** [comment]
Please update to 1.2.3 and tell me if the problem is solved.

**Comment by Anto007** [comment]
I updated to 1.2.3 and it went a bit further than before but broke off yet again :-(

```
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read, 51529 more expected)', IncompleteRead(0 bytes read, 51529 more expected))
Downloading additional data:  27%|████████▏                     | 2730/10000 [08:33<22:47,  5.32it/s]
```

**Comment by Anto007** [comment]
Just a quick update- my test with v1.2.4 is still ongoing and is now at batch 2/3. There is of course progress now and thank you very much. You're the best angel out there!

**Comment by DominikBuchner** [comment]
Haha thanks, but is it also running super slow for you? I usually get ~50 iterations per second, but today I'm only able to get around 3-4.
