### ISSUE TITLE
No version information of boldigger3. Please check if the package name correct.

### ISSUE THREAD

**Issue by Anto007** [DominikBuchner/BOLDigger3#18]
Hi @DominikBuchner,

Sorry to bother you again. I hadn't used BOLDigger3 for the past two weeks as I was away on a break. All of a sudden, I've started getting the below error when I attempted to use the tool this morning. Any idea as to what might be happening here? Thank you very much.

```
Successfully uninstalled boldigger3-1.2.4
Successfully installed boldigger3-1.2.5
(/home/user/tools/conda_python3.11_env) user@XXXXX:/data$ boldigger3 identify ASVs.fasta --db 3 --mode 3
Installing dependencies...
Switching to root user to install dependencies...
[sudo] password for user: 
Traceback (most recent call last):
  File "/home/user/tools/conda_python3.11_env/bin/boldigger3", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/boldigger3/__main__.py", line 68, in main
    latest_version = obtainer("boldigger3")
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/get_pypi_latest_version/main.py", line 40, in __call__
    raise e
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/get_pypi_latest_version/main.py", line 38, in __call__
    all_versions_web = self.get_by_spider_web(package_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/conda_python3.11_env/lib/python3.11/site-packages/get_pypi_latest_version/main.py", line 83, in get_by_spider_web
    raise ValueError(f'No version information of {package_name}. '
ValueError: No version information of boldigger3. Please check if the package name correct.
```

**Comment by DominikBuchner** [comment]
Hi there,
Pip install --upgrade get-pypi-latest-version

Best
Dominik

Jant007 ***@***.***> schrieb am So., 29. Dez. 2024, 07:35:

**Comment by Anto007** [comment]
Thank your very much @DominikBuchner ; that fixed it!
