### ISSUE TITLE
KeyError 502

### ISSUE THREAD

**Issue by LiseKlunder** [DominikBuchner/BOLDigger3#6]
Hi Dominik, 

During the download of the additional data batches, this error came up:

13:41:41: Downloading batch 10 of 42.
Downloading additional data:  82%|███████████████████████████████████████▉         | 4075/5000 [06:32<01:29, 10.38it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Scripts\boldigger3.exe\__main__.py", line 7, in <module>
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\__main__.py", line 118, in main
    additional_data_download.main(arguments.fasta_file)
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\additional_data_download.py", line 330, in main
    response = asyncio.run(as_session(chunk, semaphore))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\additional_data_download.py", line 199, in as_session
    return await tqdm.gather(*tasks, desc="Downloading additional data")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
           ^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 631, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
              ^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\additional_data_download.py", line 166, in limit_concurrency
    return await as_request(url, as_session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\additional_data_download.py", line 147, in as_request
    response = parse_record_page(response, url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\additional_data_download.py", line 77, in parse_record_page
    status = status_code_to_status[html_response.status_code]
             ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 502

**Comment by Anto007** [comment]
I encountered similar errors this morning but upgrading the BOLDigger3 package resolved this issue for me
`pip install --upgrade boldigger3`

**Comment by DominikBuchner** [comment]
Fixed with version 1.1.4!

**Comment by LiseKlunder** [comment]
It happened again...
I closed the powershell, updated and even started again from the storage file you send me

18:01:43: Downloading batch 14 of 42.
Downloading additional data:  63%|██████████████████████████████▉                  | 3152/5000 [05:26<03:11,  9.66it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Scripts\boldigger3.exe\__main__.py", line 7, in <module>
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\__main__.py", line 118, in main
    additional_data_download.main(arguments.fasta_file)
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\additional_data_download.py", line 334, in main
    response = asyncio.run(as_session(chunk, semaphore))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\additional_data_download.py", line 203, in as_session
    return await tqdm.gather(*tasks, desc="Downloading additional data")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
           ^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 631, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
              ^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\additional_data_download.py", line 170, in limit_concurrency
    return await as_request(url, as_session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\additional_data_download.py", line 151, in as_request
    response = parse_record_page(response, url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\additional_data_download.py", line 81, in parse_record_page
    status = status_code_to_status[html_response.status_code]
             ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 504

**Comment by DominikBuchner** [comment]
I added 504 to the error code list inside BOLDigger3. Fixed with update to 1.1.6.
